import coursesCardImage from "../../assets/images/coursesCardImage.png";
import avatarImage from "../../assets/images/edu1.png";

export const courses = [
  {
    id: 0,
    title: "The ultimate python course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 1,
    title: "The ultimate c++ course for beginners",
    catergory: "UI/UX Design",
    rating: 5,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 2,
    title: "The ultimate java course for beginners",
    catergory: "UI/UX Design",
    rating: 2,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 3,
    title: "The ultimate javascript course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 4,
    title: "The ultimate c course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 5,
    title: "The ultimate typescript course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 6,
    title: "The ultimate ruby course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 7,
    title: "The ultimate julia course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 8,
    title: "The ultimate matlab course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 9,
    title: "The ultimate c# course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 10,
    title: "The ultimate shakespear course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 11,
    title: "The ultimate python course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
  {
    id: 12,
    title: "The ultimate cython course for beginners",
    catergory: "UI/UX Design",
    rating: 4,
    duration: "22hr 30min",
    courseCount: 34,
    author: "Dannette P. Cervantes",
    price: "Free",
    imageUrl: coursesCardImage,
    avatarUrl: avatarImage,
  },
];
